import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className="bg-violet-100">
      <Head>
        <title>Next.js PlayGround - Tung Le</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex  p-2 ">
          <CountUp />

         
        </div>
        <div>
          <CardWithImg/>
        </div>
      </main>
    </div>
  );
}

function NavBar() {
  return (
    <nav className="navbar w-full bg-black ">
      <div className="container-lg px-0">
        <div className="flex w-full items-center">
          <a className="nav-brand mr-auto ml-0" href="#">
            Material Tailwind
          </a>
          <button
            navbar-trigger=""
            className="navbar-trigger ml-auto mr-0 mb-0 block lg:hidden"
            type="button"
            aria-controls="navigation"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-trigger-icon">
              <span className="navbar-trigger-bar mt-1">
                <span className="hidden origin-[10%_10%] rotate-45"></span>
              </span>
              <span className="bar2 navbar-trigger-bar mt-2"></span>
              <span className="bar3 navbar-trigger-bar mt-2">
                <span className="mt-mt-[0.4375rem] hidden origin-[10%_90%] -rotate-45"></span>
              </span>
            </span>
          </button>
        </div>
        <div className="collapse navbar-collapse" navbar-menu="">
          <ul className="navbar-nav">
            <li>
              <a className="nav-link" aria-current="page" href="#">
                <i className="material-icons mr-2 text-base opacity-60">
                  article
                </i>
                <span>Documantation</span>
              </a>
            </li>
            <li>
              <a className="nav-link" href="#">
                <i className="material-icons mr-2 text-base opacity-60">apps</i>
                <span>Components</span>
              </a>
            </li>
            <li className="flex">
              <a className="nav-link" href="#">
                <i className="material-icons mr-2 text-base opacity-60">
                  view_carousel
                </i>
                <span>Templates</span>
              </a>
            </li>
            <li>
              <a className="nav-link" href="#">
                <i className="fab fa-github mr-2 text-base opacity-60"></i>
                <span>Github</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
}
function CountUp() {
  let [count, setCount] = useState(0);

  return (
    <div className=" flex justify-center flex-col mt-3 rounded-md bg-violet-500 shadow-xl ">
      <div className="flex justify-center">
        <h1 className="text-black text-4xl p-1"> {count} </h1>
      </div>

      <div className="flex space-x-2 justify-center p-1">
        <button
          onClick={() => setCount(count + 1)}
          type="button"
          data-mdb-ripple="true"
          data-mdb-ripple-color="light"
          className="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
        >
          Click me
        </button>
      </div>
    </div>
  );
}
function DisplayArray1() {
  const [arr1] = useState({
    title: "Rawr",
    Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores ipsum fugit nemo, aliquid distinctio et iure laudantium itaque accusantium alias incidunt ad porro, eveniet modi, ullam aperiam obcaecati dolorem optio totam ratione inventore odio praesentium deserunt. Obcaecati consequatur soluta nam consectetur hic, atque iure corrupti, voluptatem molestiae eum veritatis. Illo, magni qui reiciendis cumque quo amet earum? Adipisci, nobis blanditiis ex ipsam asperiores earum facilis vel sit optio quam molestiae obcaecati, ea vitae aspernatur officiis debitis quas? Velit, consequuntur commodi libero, harum, quibusdam quisquam facere doloremque praesentium beatae perspiciatis debitis temporibus illo. Id et natus sint perspiciatis aliquam qui voluptate.",
      img:'//thiscatdoesnotexist.com'
  });
  return (
    <div className="p-2 rounded-md text-black card">
      
      <div className="">{arr1.title}</div>
      <div className=""> {arr1.Description}  </div>
    </div>
  );
}

// This gets called on every request

function CardWithImg() {
  return (
    <div className="flex justify-center">
      <div className=" shadow-lg bg-white max-w-xs">
        <a href="#!" data-mdb-ripple="true" data-mdb-ripple-color="light">
          <img
            className=""
            src="https://mdbootstrap.com/img/new/standard/nature/182.jpg"
            alt=""
          />
        </a>
        <div className="p-6">
          <h5 className="text-gray-900 text-xl font-medium mb-2">Card title</h5>
          <p className="text-gray-700 text-base mb-4">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
          <button
            type="button"
            className=" inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
          >
            Button
          </button>
        </div>
      </div>
    </div>
  );
}
function Comment(props) {
  return (
    <div className="card bg-sky-100 hover:bg-violet-500">
      <img src={props.picture} alt="" className="rounded " />
      <div className="card-img-overlay flex">
        <p>test</p>
        <p>test</p>
      </div>
    </div>
  );
}

function Welcome(props) {
  return (
    <h1>
      {props.message}
      Composing Components Components can refer to other components in their
      output. This lets us use the same component abstraction for any level of
      detail. A button, a form, a dialog, a screen: in React apps, all those are
      commonly expressed as components. For example, we can create an App
      component that renders Welcome many times:
    </h1>
  );
}
